config/routes.rb
Rails.application.routes.draw do
  get '/tasks', to: "tasks#index"

  post 'tasks/', to:"tasks#create"

  get 'tasks/new', to:"tasks#new"

  get 'tasks/:id', to: "tasks#show", as:"task"

  get 'tasks/:id/edit', to:"tasks#edit", as:"edit_task"

  patch 'tasks/:id', to:"tasks#update"

  delete 'tasks/:id', to:"tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#resourses :tasks.  would do it automatically

root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path

  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(params[:name])

  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    p params.require(:task).permit(:name, :action) # returns a hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :action %>
  <%= f.text_field :action %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<%= link_to "create new", tasks_new_path %>

<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <p><%= task.action %></p>
  <%= link_to task.name, task_path(task) %>
  <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

<h2><%= @task.name %></h2>
<p><%= @task.action %></p>

<%= link_to "back to index", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>